# Path to the yarrfiles configuration.
YARRF=$HOME/.yarrfiles

# Which dotfiles would you like to load? (dotfiles can be found in ~/.yarrfiles/dotfiles/*)
# Dot files may be added to ~/.yarrfiles/custom/dotfiles/
# Example format: dotfiles=(vim)
dotfiles=(vim)

# Which plugins would you like to load? (plugins can be found in ~/.yarrfiles/plugins/*)
# Custom plugins may be added to ~/.yarrfiles/custom/plugins/
# Example format: plugins=(git lol)
plugins=(git)

source $YARRF/yarrf.sh

# defaults
alias shconfig='vi ~/.bashrc'
alias reload='source ~/.bashrc'


